Update to `Readme.md`
KSoft-Si/ksoftapi.py pull request #22
Opened 2022-05-17 04:52 UTC by UnknownLITE

* Replaced invalid discord invitation link with permanent invitation link (given [here](https://github.com/KSoft-Si/issues/blob/221f0e1e3d4af9a5bcc5f4a8aa06b0d084000935/.github/ISSUE_TEMPLATE/config.yml#L7))
* Added link to the logo of Ksoft.si to [its homepage](https://ksoft.si)
* Refactored example code in the `Readme.md`

2022-05-17 15:55 UTC, devoxin requested changes

2022-05-22 16:25 UTC, UnknownLITE commented on README.md
> +        print("No lyrics found for " + query)
I'm sorry for that.
I'm not sure but that was my naughty VSCode formatter (I prefer to use Pycharm and `'`)
Should I change it back to `'`s?

2022-05-22 17:57 UTC, Devoxin commented on README.md
> +        print("No lyrics found for " + query)
Yes please

2022-07-16 10:51 UTC, UnknownLITE commented on README.md
> +[Obtain an API key (Unavailable)](https://api.ksoft.si/) | [Documentation](https://py.docs.ksoft.si/) | [Join our Discord server](https://discord.gg/7bqdQd4)
I didn't get you 🤷

2022-07-19 17:20 UTC, devoxin approved these changes

2023-11-10 03:57 UTC, merged